export type HabitTemplate = {
  name: string;
  emoji: string;
  color: string;
  frequencyType: "DAILY" | "WEEKLY" | "CUSTOM";
  frequencyDays: number;
  targetValue: string;
  targetUnit: string;
  difficulty: "EASY" | "MEDIUM" | "HARD";
  category: "Fitness" | "Mindfulness" | "Health" | "Learning" | "Productivity";
  description: string;
};

export const HABIT_TEMPLATES: HabitTemplate[] = [
  // ── Fitness ────────────────────────────────────────────────────────────────
  {
    name: "Morning Run",
    emoji: "🏃",
    color: "#f97316",
    frequencyType: "DAILY",
    frequencyDays: 7,
    targetValue: "30",
    targetUnit: "min",
    difficulty: "MEDIUM",
    category: "Fitness",
    description: "Start the day with a refreshing run",
  },
  {
    name: "Push-ups",
    emoji: "💪",
    color: "#ef4444",
    frequencyType: "DAILY",
    frequencyDays: 7,
    targetValue: "50",
    targetUnit: "reps",
    difficulty: "MEDIUM",
    category: "Fitness",
    description: "Build upper body strength daily",
  },
  {
    name: "Gym Workout",
    emoji: "🏋️",
    color: "#dc2626",
    frequencyType: "CUSTOM",
    frequencyDays: 3,
    targetValue: "60",
    targetUnit: "min",
    difficulty: "HARD",
    category: "Fitness",
    description: "Strength training sessions per week",
  },
  {
    name: "Stretching",
    emoji: "🤸",
    color: "#fb923c",
    frequencyType: "DAILY",
    frequencyDays: 7,
    targetValue: "10",
    targetUnit: "min",
    difficulty: "EASY",
    category: "Fitness",
    description: "Daily flexibility and mobility work",
  },
  {
    name: "Steps Goal",
    emoji: "👟",
    color: "#f59e0b",
    frequencyType: "DAILY",
    frequencyDays: 7,
    targetValue: "10000",
    targetUnit: "steps",
    difficulty: "MEDIUM",
    category: "Fitness",
    description: "Hit your daily step target",
  },

  // ── Mindfulness ────────────────────────────────────────────────────────────
  {
    name: "Meditation",
    emoji: "🧘",
    color: "#8b5cf6",
    frequencyType: "DAILY",
    frequencyDays: 7,
    targetValue: "10",
    targetUnit: "min",
    difficulty: "EASY",
    category: "Mindfulness",
    description: "Daily mindfulness practice",
  },
  {
    name: "Journaling",
    emoji: "📔",
    color: "#a855f7",
    frequencyType: "DAILY",
    frequencyDays: 7,
    targetValue: "5",
    targetUnit: "min",
    difficulty: "EASY",
    category: "Mindfulness",
    description: "Reflect and write about your day",
  },
  {
    name: "Gratitude Log",
    emoji: "🙏",
    color: "#ec4899",
    frequencyType: "DAILY",
    frequencyDays: 7,
    targetValue: "3",
    targetUnit: "items",
    difficulty: "EASY",
    category: "Mindfulness",
    description: "Write 3 things you're grateful for",
  },
  {
    name: "Deep Breathing",
    emoji: "🌬️",
    color: "#06b6d4",
    frequencyType: "DAILY",
    frequencyDays: 7,
    targetValue: "5",
    targetUnit: "min",
    difficulty: "EASY",
    category: "Mindfulness",
    description: "Breathing exercises for calm",
  },

  // ── Health ─────────────────────────────────────────────────────────────────
  {
    name: "Drink Water",
    emoji: "💧",
    color: "#3b82f6",
    frequencyType: "DAILY",
    frequencyDays: 7,
    targetValue: "8",
    targetUnit: "glasses",
    difficulty: "EASY",
    category: "Health",
    description: "Stay hydrated throughout the day",
  },
  {
    name: "Sleep 8 Hours",
    emoji: "😴",
    color: "#6366f1",
    frequencyType: "DAILY",
    frequencyDays: 7,
    targetValue: "8",
    targetUnit: "hrs",
    difficulty: "MEDIUM",
    category: "Health",
    description: "Get a full night's rest",
  },
  {
    name: "Eat Vegetables",
    emoji: "🥗",
    color: "#22c55e",
    frequencyType: "DAILY",
    frequencyDays: 7,
    targetValue: "5",
    targetUnit: "servings",
    difficulty: "MEDIUM",
    category: "Health",
    description: "5 servings of vegetables daily",
  },
  {
    name: "No Sugar",
    emoji: "🚫",
    color: "#ef4444",
    frequencyType: "DAILY",
    frequencyDays: 7,
    targetValue: "",
    targetUnit: "",
    difficulty: "HARD",
    category: "Health",
    description: "Avoid added sugar for the day",
  },
  {
    name: "Take Vitamins",
    emoji: "💊",
    color: "#10b981",
    frequencyType: "DAILY",
    frequencyDays: 7,
    targetValue: "",
    targetUnit: "",
    difficulty: "EASY",
    category: "Health",
    description: "Daily supplement routine",
  },

  // ── Learning ───────────────────────────────────────────────────────────────
  {
    name: "Read Books",
    emoji: "📚",
    color: "#f59e0b",
    frequencyType: "DAILY",
    frequencyDays: 7,
    targetValue: "20",
    targetUnit: "pages",
    difficulty: "EASY",
    category: "Learning",
    description: "Read a little bit every day",
  },
  {
    name: "Learn a Language",
    emoji: "🌍",
    color: "#14b8a6",
    frequencyType: "DAILY",
    frequencyDays: 7,
    targetValue: "15",
    targetUnit: "min",
    difficulty: "MEDIUM",
    category: "Learning",
    description: "Daily language practice session",
  },
  {
    name: "Online Course",
    emoji: "💻",
    color: "#6366f1",
    frequencyType: "CUSTOM",
    frequencyDays: 3,
    targetValue: "30",
    targetUnit: "min",
    difficulty: "MEDIUM",
    category: "Learning",
    description: "Make progress on your courses",
  },

  // ── Productivity ───────────────────────────────────────────────────────────
  {
    name: "Deep Work",
    emoji: "🎯",
    color: "#8b5cf6",
    frequencyType: "DAILY",
    frequencyDays: 5,
    targetValue: "90",
    targetUnit: "min",
    difficulty: "HARD",
    category: "Productivity",
    description: "Focused, distraction-free work",
  },
  {
    name: "No Social Media",
    emoji: "📵",
    color: "#f43f5e",
    frequencyType: "DAILY",
    frequencyDays: 7,
    targetValue: "",
    targetUnit: "",
    difficulty: "HARD",
    category: "Productivity",
    description: "Stay off social media for the day",
  },
  {
    name: "Plan Tomorrow",
    emoji: "📝",
    color: "#84cc16",
    frequencyType: "DAILY",
    frequencyDays: 7,
    targetValue: "",
    targetUnit: "",
    difficulty: "EASY",
    category: "Productivity",
    description: "Spend 5 min planning the next day",
  },
];

export const TEMPLATE_CATEGORIES = ["Fitness", "Mindfulness", "Health", "Learning", "Productivity"] as const;
export type TemplateCategory = typeof TEMPLATE_CATEGORIES[number];

export const CATEGORY_META: Record<TemplateCategory, { emoji: string; color: string }> = {
  Fitness:      { emoji: "🏋️", color: "#f97316" },
  Mindfulness:  { emoji: "🧘", color: "#8b5cf6" },
  Health:       { emoji: "💚", color: "#22c55e" },
  Learning:     { emoji: "📚", color: "#f59e0b" },
  Productivity: { emoji: "🎯", color: "#6366f1" },
};
